# Generated by Django 6.0.1 on 2026-02-13 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', code='Invalid phone number', message='Enter a valid phone number in the format 9876543210 (10 digits starting with 6, 7, 8, or 9)')]),
        ),
    ]
