# Generated by Django 6.0.1 on 2026-03-27 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', code='invalid_phone_number', message='Enter a valid phone number in the format 9876543210 (10 digits starting with 6, 7, 8, or 9)')]),
        ),
    ]
